repos:
  - repo: local
    hooks:
      - id: make-check
        name: Run make check
        entry: make check
        language: system
        pass_filenames: false
        always_run: true
      
      - id: validate-spec-examples
        name: Validate spec examples
        entry: make validate-examples
        language: system
        pass_filenames: false
        files: ^(docs/.*\.md|wassden/.*\.py|tests/integration/test_spec_examples\.py)$